spring:
  application:
    name: api-gateway
  profiles:
    active: development
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: SpringMicroservices
  resource: user-service
  public-client: true
  security-constraints[0]:
    authRoles:
      - user
    securityCollections[0]:
      patterns:
        - /users/*
